device: 0
save_dir: 'log'

data:
  train_file: 'data/data.clean/english-train.pkl'
  val_file: 'data/data.clean/english-val.pkl'
  test_file: 'data/data.clean/english-test.pkl'
  vocab_type: 'max_size'
  vocab_size: 10000
  min_freq: 2

model:
  model_name: 'HNPCFG'
  NT: 4096
  T: 8192
  s_dim: 512
  tau_root_init: 1.96639395077448
  tau_rule_init: 12.737609884132324
  tau_term_init: 9.242005338216677
  complex_normalization: false

train:
  batch_size: 16
  max_epoch: 30
  max_len: 40
  curriculum: 0
  start_len: 30
  increment: 1
  patience: 10
  clip: 3

test:
  batch_size: 16
  max_tokens: 100
  bucket: 32
  decode: 'mbr'
  sampler: 'batch'

optimizer:
  name: 'adam'
  lr: 0.002576751484771699
  mu: 0.75
  nu: 0.999
  relation_weight_decay: 0.0

wandb:
  enabled: true
  project: 'hol-pcfg'
  group: 'ablation'
  run_name: 'hnpcfg-ablation-ll-en-no_cnorm'
  tags: ['hnpcfg', 'nt4096', 'p3-eji18kkl', 'tab-ablation', 'paper', 'en', 'abl:no_cnorm']
